name: Release

on:
  push:
    tags:
      - "v*.*.*"   # örn: v0.2.0

jobs:
  publish-tauri:
    runs-on: windows-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps
        run: npm install

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build and publish Tauri app
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: .
          tagName: ${{ github.ref_name }}          # v0.2.0
          releaseName: "XTime ${{ github.ref_name }}"
          releaseDraft: false
          prerelease: false